acl duckdarsh {
  100.104.174.121;
  100.110.171.14;
  100.114.221.109;
	192.168.0.0/24;
  172.16.0.0/12;
	127.0.0.1;
	localhost;
};
options {
    forwarders { 
       1.1.1.1; 
       1.0.0.1;
   };
 
    allow-query { duckdarsh; };
    allow-query-cache { duckdarsh; };
    allow-recursion {duckdarsh; };
    qname-minimization strict;
    dnssec-validation auto;
};

zone "duckdarsh.home" IN {
    type master;
    file "/var/lib/bind/duckdarsh.home.zone";
};

zone "vulpes.smials" IN {
    type master;
    file "/var/lib/bind/vulpes.smials.zone";
};
